services:
    np_redis:
        container_name: np_redis
        image: redis:7.4.1-alpine
        restart: unless-stopped
        volumes:
            - redis_vol:/data
        environment:
            - REDIS_PASSWORD=1234567
        command: ["redis-server", "--requirepass", "1234567"]
        ports:
            - 6380:6379
        networks:
            - np_network

    nginx_proxy:
        container_name: nginx_proxy
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            - np_network
volumes:
    redis_vol:

networks:
    np_network:
        name: np_network
        driver: bridge
