services:
    # mysql:
    #     container_name: mysql
    #     image: mysql:8.0.33
    #     restart: always
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=myPassWord
    #         - MYSQL_DATABASE=test
    #     ports:
    #         - 3308:3306
    #     volumes:
    #         - db_vol:/var/lib/mysql
    # - .backup-db:/docker-entrypoint-initdb.d

    np_redis:
        container_name: np_redis
        image: redis:7.4.1-alpine
        restart: always
        volumes:
            - redis_vol:/data
        environment:
            - REDIS_PASSWORD=1234567
        ports:
            - 6380:6379
        networks:
            - np_network

    np_api:
        container_name: np_api
        depends_on:
            - np_redis
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        restart: always
        ports:
            - 4000:4000
        networks:
            - np_network

volumes:
    db_vol:
    redis_vol:

networks:
    np_network:
        name: np_network
        driver: bridge
